apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-pod-logs-binding
subjects:
- kind: ServiceAccount
  name: default  # Replace with your service account name
  namespace: default  # Replace with the namespace of your service account
roleRef:
  kind: ClusterRole
  name: read-pod-logs
  apiGroup: rbac.authorization.k8s.io
