# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-commerce
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: e-commerce
          image: udayakrishnan/e-commerce:latest
        

