apiVersion: v1
kind: Service
metadata: 
  name: e-commerce-srv
spec:
  type: NodePort
  selector:
    app: e-commerce
  ports: 
    - name: e-commerce
      protocol: TCP
      port: 8081
      targetPort: 8081