name: echo-elite

on: 
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        npm install
        # Ensure all modules are installed correctly
        if [ ! -f ./node_modules/mongoose/lib/helpers/populate/setPopulatedVirtualValue.js ]; then
          echo "setPopulatedVirtualValue.js not found, reinstalling mongoose"
          npm uninstall mongoose
          npm install mongoose
        fi
        npm start

