name: echo-elite

on: 
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        rm -rf node_modules package-lock.json
        npm install
        npm start
